### ISSUE TITLE
Dependencies not relocated

### ISSUE THREAD

**Issue by H3xtyy** [OskarsMC-Plugins/execute#1]
Here's the error when on proxy I have this 2 plugins.

```
[14:45:48] [Velocity Async Event Executor - #0/WARN]: *******************************************
Plugin 'execute 0.1.0' has shaded the library 'HikariCP' but did not relocate it. This may or may not pose problems. Contact the author of this plugin and tell them to relocate their dependencies. Unrelocated class detected was com.zaxxer.hikari.HikariConfig
*******************************************
[14:45:49] [Velocity Async Event Executor - #0/INFO]: Conducting START...
[14:45:49] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-MariaDB - Starting...
[14:45:49] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to libertybans
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.mariadb.jdbc.MariaDbDataSource
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:96) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:314) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:108) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[?:?]
	at space.arim.libertybans.core.database.DatabaseSettings.setHikariConfig(DatabaseSettings.java:132) ~[?:?]
	at space.arim.libertybans.core.database.DatabaseSettings.createDataSource(DatabaseSettings.java:89) ~[?:?]
	at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:100) ~[?:?]
	at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:75) ~[?:?]
	at space.arim.libertybans.core.database.DatabaseManager.startup(DatabaseManager.java:92) ~[?:?]
	at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:71) ~[?:?]
	at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:125) ~[?:?]
	at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:62) ~[?:?]
	at space.arim.libertybans.env.velocity.VelocityInitializer.initialize(VelocityInitializer.java:81) ~[?:?]
	at space.arim.libertybans.env.velocity.VelocityPlugin.onProxyInitialize(VelocityPlugin.java:59) ~[?:?]
	at space.arim.libertybans.env.velocity.Lmbda$14.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.mariadb.jdbc.MariaDbDataSource
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity.jar:3.1.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:83) ~[?:?]
	... 21 more
```

**Comment by OskarZyg** [comment]
I'm not sure why HikariCP is in the jar, but I'll fix this by relocating the dependencies.

**Comment by OskarZyg** [comment]
Does [this build](https://github.com/OskarsMC-Plugins/execute/suites/4801555630/artifacts/134720473) solve the issue?

**Comment by H3xtyy** [comment]
> 

Yep, it's working. Thanks for the fix 😃
